CPPFLAGS=-std=gnu++98 -Werror -Wall -pedantic
all: cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4
cyoa-step1: cyoa-step1.cpp page.cpp story.cpp
	g++ $(CPPFLAGS) -o cyoa-step1 cyoa-step1.cpp page.cpp story.cpp
cyoa-step2: cyoa-step2.cpp page.cpp story.cpp
	g++ $(CPPFLAGS) -o cyoa-step2 cyoa-step2.cpp page.cpp story.cpp
cyoa-step3: cyoa-step3.cpp page.cpp story.cpp
	g++ $(CPPFLAGS) -o cyoa-step3 cyoa-step3.cpp page.cpp story.cpp
cyoa-step4: cyoa-step4.cpp page.cpp story.cpp
	g++ $(CPPFLAGS) -o cyoa-step4 cyoa-step4.cpp page.cpp story.cpp
